### ISSUE TITLE
Intercepting "E" key with PAW open

### ISSUE THREAD

**Issue by Divstator** [linuxgurugamer/PartInfo#3] opened 2020-08-04 02:09 UTC
This is breaking "Breaking Ground" deployable science experiments. For some reason, when you try to place the experiment, which requires hitting the "E" key, it doesn't do anything. I suspect that somehow this mod is intercepting the "E" key when a PAW is open. I haven't looked at it thoroughly though.

**Comment by linuxgurugamer** [comment] 2020-08-04 11:42
This mod is not intercepting any keys, at all.  The part module only opens a small window with a couple of buttons, there is nothing watching for keystrokes.

I'll try it out to verify this later this evening, but until then, can you please get me a copy of the Player.log file?

**Comment by Divstator** [comment] 2020-08-06 01:22
[https://www.dropbox.com/s/eqwaqp4yofofsgr/Player.log?dl=0](url)

Wow, you were quicker than I expected. I figured you would need the log file, but while I was getting it I was delving to the code. That involved getting set up again with VS 2017 and trying to locate reference dlls etc. From looking at the code it looked like it might be ClickThroughBlocker since it locks flight inputs? That doesn't really make sense though. Anyways, I tried switching the different focus methods and that didn't make any difference.

When trying to deploy a "Breaking ground" science experiment, once you click on the "placement icon" you have to use "E" to drop it and place it. It just makes clicking sound without placing it. The "J" and "L" keys work fine rotating it and the "Escape" key will back you out of it just fine.

Let me know if there is anything else I can do to assist.

**Comment by linuxgurugamer** [comment] 2020-08-06 01:35
Actually, a video showing the issue would be useful.   I'm wondering if the location of the mouse might be the cause.  If you selected FocusFollowsClick, then it's possible that if you have a window  open, that the input will be locked for anything else.  Try clicking on an empty part of the window before hitting the E

**Comment by Divstator** [comment] 2020-08-06 01:59
I don't have any screen capture video software set up I'm afraid.

I tried clicking inside the window all over and outside the window and dismissing the window. I've also tried clearing the input locks using ClickThroughBlocker. I tried to find where Squad put the keybinds as well in case the walking on it somehow. I'm open for suggestions on other things to try.

**Comment by linuxgurugamer** [comment] 2020-08-06 02:06
Regarding screen capture, you can install OBS, it's free and does a good job.
Other than that, I'll have to look at your log file

**Comment by linuxgurugamer** [comment] 2020-08-06 02:09
Well, the log file has a single exception:
`
Uploading Crash Report
NullReferenceException
  at (wrapper managed-to-native) UnityEngine.Behaviour.set_enabled(UnityEngine.Behaviour,bool)
  at ModuleInventoryPart+<CreatePartObject>d__63.MoveNext () [0x005a3] in <c1858a3f77504bd1aaa946fdccf84670>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00027] in <5aeafee3fea24f37abd1315553f2cfa6>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
`
and it's right at the place where you are having the problem
I'll try to reproduce it

**Comment by linuxgurugamer** [comment] 2020-08-06 02:10
Can you please send me the contents of your folder:

000_MyCustomCFGs

Save file would also be useful

**Comment by Divstator** [comment] 2020-08-06 02:23
Okay
This is on KSP 1.10.1 also.

Video btw
[https://www.dropbox.com/s/tc3lmccy7jshfn5/2020-08-05_21-09-49.mkv?dl=0](url)

Save file:
[https://www.dropbox.com/s/u3sfuclm6scacql/persistent.sfs?dl=0](url)

Custom CFG folder:
[https://www.dropbox.com/sh/oyj25n3aonboe4z/AACaOkZSc2w2TPMOlM2Z5Bxla?dl=0](url)

I'm not sure if you'll be able to see all the files in the folder, but I think I only have two cfg's in there. I do have one of them set up for Patch Manager though. I'm still working on them.

[https://www.dropbox.com/s/z6o211cc1rh4qz5/CustomProbeBattery.cfg?dl=0](url)

[https://www.dropbox.com/s/mjv11ibpfah3yez/CFGForKelly.cfg?dl=0](url)

[https://www.dropbox.com/s/7up2vkcsju2ly0x/RepairForColorCodedCannisters.cfg?dl=0](url)

**Comment by linuxgurugamer** [comment] 2020-08-06 02:34
I don't know if you have Discord installed, but if you do, you can contact me on it right now, I have some questions:

https://discord.gg/ptD66d

**Comment by linuxgurugamer** [comment] 2020-08-06 02:36
Ok, you got me confused when  you said that the letter E was placing the parts.  It's really the space bar, and I do see the problem

**Comment by linuxgurugamer** [comment] 2020-08-06 02:47
Fixed in new release

**Closed as completed by linuxgurugamer** 2020-08-06 02:47 UTC
